### ISSUE TITLE
Failed to parse answer: strconv.Atoi: parsing "": invalid syntax

### ISSUE THREAD

**Issue by McCoyAle** [McCoyAle/arithmamom#30]
This error seems to involve the input field, but the logic needs to be revisited. The following should happen:

- The page displays. 
- The name of the user is asked (with user logic it should be able to retrieve it without prompting. Not builtin yet)
- The user is welcome. 
- Mathematical Operation is selected.
- A question is generated and response is requested. 
- Response submitted 
- Response evaluated and then nagivate to the next question. 

I am accessing via local host rather than passing field input via the URL so seems the code will need to be revisited at a later time. 

<img width="571" alt="Screenshot 2024-03-22 at 3 44 33 PM" src="https://github.com/McCoyAle/arithmamom/assets/25905730/1b271dba-4167-4763-b7b8-f4218ae8f8d5">

**Comment by TechinMama** [comment]
Resolved by #31
